# Generated by Django 3.0.2 on 2020-10-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.EmailField(max_length=254)),
                ('scontact', models.CharField(max_length=30)),
            ],
        ),
    ]
